site_recipe/recipe/urls.py
from django.urls import path
from .views import index, recipes, get_recipes_on_name, get_categories, get_ingredients, \
    get_recipes_on_categories, get_recipes_on_ingredients, update_recipe
from .views import add_recipe, add_categories, add_ingredients

urlpatterns = [
    path('', index, name='index'),
    path('recipes/', recipes, name='recipes'),
    path('recipe_create/', add_recipe, name='add_recipe'),
    path('recipe_update/<str:recipe_name>/', update_recipe, name='update_recipe'),
    path('recipes/<str:recipe_name>/', get_recipes_on_name, name='recipe'),
    path('categories/', get_categories, name='categories'),
    path('categories/<str:category>', get_recipes_on_categories, name='category_recipes'),
    path('category_create/', add_categories, name='add_categories'),
    path('ingredients/', get_ingredients, name='ingredients'),
    path('ingredient_create/', add_ingredients, name='add_ingredients'),
    path('ingredients/<str:ingredient>', get_recipes_on_ingredients, name='ingredient_recipes'),

]

site_recipe/site_recipe/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from recipe.views import index


urlpatterns = [
    path('admin/', admin.site.urls),
    path('recipe/', include('recipe.urls')),
    path('users/', include('userapp.urls', namespace='userapp')),
    path('', index),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + \
               static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

site_recipe/userapp/urls.py
from django.urls import path
from .views import LoginView, logout_user, ProfileUser, UserPasswordChange
from .forms import LoginUserForm, RegisterUserForm
from django.views.generic import CreateView
from django.contrib.auth.views import PasswordChangeView, PasswordChangeDoneView, PasswordResetView, \
    PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView
from django.urls import reverse_lazy

app_name = 'userapp'

urlpatterns = [
    path('login/', LoginView.as_view(template_name='userapp/login.html', authentication_form=LoginUserForm,
                                     extra_context={'title': 'Авторизация'}), name='login'),
    path('logout/', logout_user, name='logout'),
    path('register/', CreateView.as_view(template_name='userapp/register.html', form_class=RegisterUserForm,
                                         extra_context={'title': 'Регистрация'},
                                         success_url=reverse_lazy('userapp:login')), name='register'),
    path('profile/', ProfileUser.as_view(template_name='userapp/profile.html'), name='profile'),
    path('password-change/', UserPasswordChange.as_view(), name='password_change'),
    path('password-change/done/', PasswordChangeDoneView.as_view(template_name='userapp/password_change_done.html'),
         name='password_change_done'),
    path('password-reset/',
         PasswordResetView.as_view(template_name="userapp/password_reset_form.html",
                                   email_template_name="userapp/password_reset_email.html",
                                   success_url=reverse_lazy("userapp:password_reset_done")),
         name='password_reset'),
    path('password-reset/done/',
         PasswordResetDoneView.as_view(template_name="userapp/password_reset_done.html"),
         name='password_reset_done'),
    path('password-reset/<uidb64>/<token>/',
         PasswordResetConfirmView.as_view(template_name="userapp/password_reset_confirm.html",
                                          success_url=reverse_lazy("userapp:password_reset_complete")),
         name='password_reset_confirm'),
    path('password-reset/complete/',
         PasswordResetCompleteView.as_view(template_name="userapp/password_reset_complete.html"),
         name='password_reset_complete'),
]

site_recipe/userapp/models.py
from django.db import models


# Create your models here.

site_recipe/userapp/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, PasswordChangeForm


class LoginUserForm(AuthenticationForm):
    username = forms.CharField(label='Логин', widget=forms.TextInput(attrs={'class': 'form-input'}))
    password = forms.CharField(label='Пароль', widget=forms.PasswordInput(attrs={'class': 'form-input'}))

    class Meta:
        model = get_user_model()
        fields = ['username', 'password']


class RegisterUserForm(UserCreationForm):
    username = forms.CharField(label="Логин", widget=forms.TextInput(attrs={'class': 'form-input'}))
    password1 = forms.CharField(label="Пароль", widget=forms.PasswordInput(attrs={'class': 'form-input'}))
    password2 = forms.CharField(label="Повтор пароля", widget=forms.PasswordInput(attrs={'class': 'form-input'}))

    class Meta:
        model = get_user_model()
        fields = ['username', 'email', 'first_name', 'last_name', 'password1', 'password2']
        labels = {
            'email': 'E-mail',
            'first_name': 'Имя',
            'last_name': 'Фамилия',
        }
        widgets = {
            'email': forms.TextInput(attrs={'class': 'form-input'}),
            'first_name': forms.TextInput(attrs={'class': 'form-input'}),
            'last_name': forms.TextInput(attrs={'class': 'form-input'}),
        }

    def clean_email(self):
        email = self.cleaned_data['email']
        if get_user_model().objects.filter(email=email).exists():
            raise forms.ValidationError("Такой E-mail уже существует!")
        return email


class ProfileUserForm(forms.ModelForm):
    username = forms.CharField(disabled=True, label='Логин', widget=forms.TextInput(attrs={'class': 'form-input'}))
    email = forms.CharField(disabled=True, label='E-mail', widget=forms.TextInput(attrs={'class': 'form-input'}))

    class Meta:
        model = get_user_model()
        fields = ['username', 'email', 'first_name', 'last_name']
        labels = {
            'first_name': 'Имя',
            'last_name': 'Фамилия',
        }
        widgets = {
            'first_name': forms.TextInput(attrs={'class': 'form-input'}),
            'last_name': forms.TextInput(attrs={'class': 'form-input'}),
        }


class UserPasswordChangeForm(PasswordChangeForm):
    old_password = forms.CharField(label="Старый пароль", widget=forms.PasswordInput(attrs={'class': 'form-input'}))
    new_password1 = forms.CharField(label="Новый пароль", widget=forms.PasswordInput(attrs={'class': 'form-input'}))
    new_password2 = forms.CharField(label="Подтверждение пароля",
                                    widget=forms.PasswordInput(attrs={'class': 'form-input'}))

site_recipe/userapp/views.py
from django.contrib.auth import logout, get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LoginView, PasswordChangeView
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.views.generic import UpdateView

from .forms import LoginUserForm, ProfileUserForm, UserPasswordChangeForm


class LoginUser(LoginView):
    authentication_form = LoginUserForm
    template_name = 'userapp/login.html'
    extra_context = {'title': 'Авторизация'}


def logout_user(request):
    logout(request)
    return redirect('userapp:login')


class ProfileUser(LoginRequiredMixin, UpdateView):
    model = get_user_model()
    form_class = ProfileUserForm
    template_name = 'userapp/profile.html'
    extra_context = {'title': "Профиль пользователя"}

    def get_success_url(self):
        return reverse_lazy('userapp:profile')

    def get_object(self, queryset=None):
        return self.request.user


class UserPasswordChange(PasswordChangeView):
    form_class = UserPasswordChangeForm
    success_url = reverse_lazy("userapp:password_change_done")
    template_name = "userapp/password_change_form.html"
    extra_context = {'title': "Изменение пароля"}

site_recipe/userapp/templates/userapp/login.html
{% extends 'base.html' %}

{% block content %}


<h3 class="text-success font-bold display-6 text-center">Авторизация</h3>

<form method="post" >
    {% csrf_token %}
    <input type="hidden" name="next" value="{{ next }}" />
    <table class="mt-xl-4">

        {{ form.as_table }}
    </table>
    <button type="submit" class="mt-3 hover:bg-yellow-300 hover:text-black btn btn-success">Войти</button>
</form>
<hr>
<button class="mt-xl-4 mb-3"><a class="hover:bg-yellow-300 hover:text-black btn btn-success"
                                href="{% url 'userapp:password_reset' %}">Забыли пароль?</a></button>
{% endblock %}

site_recipe/userapp/templates/userapp/password_change_done.html
{% extends 'base.html' %}
 
{% block content %}

<h1>Пароль успешно изменен!</h1>

<p >Вы успешно изменили пароль. <a href="{% url 'userapp:profile' %}">Вернуться в профиль.</a></p>
{% endblock %}

site_recipe/userapp/templates/userapp/password_change_form.html
{% extends 'base.html' %}
 
{% block content %}



<h3 class="text-success font-bold display-6 text-center">Изменение пароля</h3>

<form method="post" >
    {% csrf_token %}
    <table class="mt-xl-4">
        {{ form.as_table }}
    </table>
    <button type="submit" class="mt-3 hover:bg-yellow-300 hover:text-black btn btn-success">Изменить пароль</button>
</form>


 
{% endblock %}

site_recipe/userapp/templates/userapp/password_reset_complete.html
{% extends 'base.html' %}
 
{% block content %}
<h1>Пароль изменен</h1>
 
<p >Поздравляем! Вы успешно изменили пароль своего аккаунта. Используйте его для
  <a href="{% url 'userapp:login' %}">входа в систему</a>.</p>
 
{% endblock %}

site_recipe/userapp/templates/userapp/password_reset_confirm.html
{% extends 'base.html' %}
 
{% block content %}
<h1>Новый пароль</h1>
 
<form method="post">
    {% csrf_token %}
    <div class="form-error">{{ form.non_field_errors }}</div>
    {% for f in form %}
    <p ><label class="form-label" for="{{ f.id_for_label }}">{{f.label}}: </label>{{ f }}</p>
    <div class="form-error">{{ f.errors }}</div>
    {% endfor %}
 
    <p ><button type="submit">Сохранить</button></p>
</form>
 
{% endblock %}

site_recipe/userapp/templates/userapp/password_reset_done.html
{% extends "base.html" %}
{% load i18n %}
 
{% block content %}
<h1>Сброс пароля</h1>
<p >{% translate 'We’ve emailed you instructions for setting your password, if an account exists with the email you entered. You should receive them shortly.' %}</p>
<p >{% translate 'If you don’t receive an email, please make sure you’ve entered the address you registered with, and check your spam folder.' %}</p>
{% endblock %}

site_recipe/userapp/templates/userapp/password_reset_email.html
{% load i18n %}{% autoescape off %}
{% blocktranslate %}You're receiving this email because you requested a password reset for your user account at {{ site_name }}.{% endblocktranslate %}

{% translate "Please go to the following page and choose a new password:" %}
{% block reset_link %}
{{ protocol }}://{{ domain }}{% url 'userapp:password_reset_confirm' uidb64=uid token=token %}
{% endblock %}
{% translate 'Your username, in case you’ve forgotten:' %} {{ user.get_username }}

{% translate "Thanks for using our site!" %}

{% blocktranslate %}The {{ site_name }} team{% endblocktranslate %}

{% endautoescape %}

site_recipe/userapp/templates/userapp/password_reset_form.html
{% extends 'base.html' %}
 
{% block content %}
<!--<h1>Восстановление пароля</h1>-->
<!-- -->
<!--<form method="post">-->
<!--    {% csrf_token %}-->
<!--{% for f in form %}-->
<!--<p ><label class="form-label" for="{{ f.id_for_label }}">{{f.label}}: </label>{{ f }}</p>-->
<!--<div class="form-error">{{ f.errors }}</div>-->
<!--{% endfor %}-->
<!-- -->
<!--    <p ><button type="submit">Сбросить по E-mail</button></p>-->
<!--</form>-->

<h3 class="text-success font-bold display-6 text-center">Восстановление пароля</h3>

<form method="post" >
    {% csrf_token %}
    <table class="mt-xl-4">
        {{ form.as_table }}
    </table>
    <button type="submit" class="mt-3 hover:bg-yellow-300 hover:text-black btn btn-success">Сбросить по E-mail</button>
</form>
 
{% endblock %}

site_recipe/userapp/templates/userapp/profile.html
{% extends 'base.html' %}

{% block content %}


<h3 class="text-success font-bold display-6 text-center">Профиль</h3>

<form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <table class="mt-xl-4">
        {{ form.as_table }}
    </table>
    <button type="submit" class="mt-3 hover:bg-yellow-300 hover:text-black btn btn-success">Сохранить</button>
</form>
<hr>
<button class="mt-xl-4 mb-3"><a class="hover:bg-yellow-300 hover:text-black btn btn-success"
                                href="{% url 'userapp:password_change' %}">Сменить пароль</a></button>


{% endblock %}

site_recipe/userapp/templates/userapp/register.html
{% extends 'base.html' %}

{% block content %}

<!--<h1>Регистрация</h1>-->
<!--<form method="post">-->
<!--    {% csrf_token %}-->
<!--    <input type="hidden" name="next" value="{{ next }}" />-->
<!--    <table>-->
<!--    {{ form.as_table }}-->
<!--    </table>-->
<!--    <p><button type="submit">Регистрация</button> </p>-->
<!--</form>-->



<h3 class="text-success font-bold display-6 text-center">Регистрация</h3>

<form method="post" >
    {% csrf_token %}
    <input type="hidden" name="next" value="{{ next }}" />
    <table class="mt-xl-4">
        {{ form.as_table }}
    </table>
    <button type="submit" class="mt-3 hover:bg-yellow-300 hover:text-black btn btn-success">Зарегестрироваться</button>
</form>

{% endblock %}

site_recipe/userapp/templates/userapp/register_done.html
{% extends 'base.html' %}
 
{% block content %}
<h1>Добро пожаловать!</h1>
 
<p >Вы успешно зарегистрировались на сайте! Для входа в систему необходимо авторизоваться по этой <a href="{% url 'userapp:login' %}">ссылке</a>
</p>
{% endblock %}