site_recipe/recipe/urls.py
from django.urls import path
from .views import index, recipes, get_recipes_on_name, get_categories, get_ingredients, \
    get_recipes_on_categories, get_recipes_on_ingredients, update_recipe
from .views import add_recipe, add_categories, add_ingredients

urlpatterns = [
    path('', index, name='index'),
    path('recipes/', recipes, name='recipes'),
    path('recipe_create/', add_recipe, name='add_recipe'),
    path('recipe_update/<str:recipe_name>/', update_recipe, name='update_recipe'),
    path('recipes/<str:recipe_name>/', get_recipes_on_name, name='recipe'),
    path('categories/', get_categories, name='categories'),
    path('categories/<str:category>', get_recipes_on_categories, name='category_recipes'),
    path('category_create/', add_categories, name='add_categories'),
    path('ingredients/', get_ingredients, name='ingredients'),
    path('ingredient_create/', add_ingredients, name='add_ingredients'),
    path('ingredients/<str:ingredient>', get_recipes_on_ingredients, name='ingredient_recipes'),

]

site_recipe/site_recipe/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from recipe.views import index


urlpatterns = [
    path('admin/', admin.site.urls),
    path('recipe/', include('recipe.urls')),
    path('users/', include('userapp.urls', namespace='userapp')),
    path('', index),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + \
               static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

site_recipe/userapp/urls.py
from django.urls import path
from .views import LoginView, logout_user, ProfileUser, UserPasswordChange
from .forms import LoginUserForm, RegisterUserForm
from django.views.generic import CreateView
from django.contrib.auth.views import PasswordChangeView, PasswordChangeDoneView, PasswordResetView, \
    PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView
from django.urls import reverse_lazy

app_name = 'userapp'

urlpatterns = [
    path('login/', LoginView.as_view(template_name='userapp/login.html', authentication_form=LoginUserForm,
                                     extra_context={'title': 'Авторизация'}), name='login'),
    path('logout/', logout_user, name='logout'),
    path('register/', CreateView.as_view(template_name='userapp/register.html', form_class=RegisterUserForm,
                                         extra_context={'title': 'Регистрация'},
                                         success_url=reverse_lazy('userapp:login')), name='register'),
    path('profile/', ProfileUser.as_view(template_name='userapp/profile.html'), name='profile'),
    path('password-change/', UserPasswordChange.as_view(), name='password_change'),
    path('password-change/done/', PasswordChangeDoneView.as_view(template_name='userapp/password_change_done.html'),
         name='password_change_done'),
    path('password-reset/',
         PasswordResetView.as_view(template_name="userapp/password_reset_form.html",
                                   email_template_name="userapp/password_reset_email.html",
                                   success_url=reverse_lazy("userapp:password_reset_done")),
         name='password_reset'),
    path('password-reset/done/',
         PasswordResetDoneView.as_view(template_name="userapp/password_reset_done.html"),
         name='password_reset_done'),
    path('password-reset/<uidb64>/<token>/',
         PasswordResetConfirmView.as_view(template_name="userapp/password_reset_confirm.html",
                                          success_url=reverse_lazy("userapp:password_reset_complete")),
         name='password_reset_confirm'),
    path('password-reset/complete/',
         PasswordResetCompleteView.as_view(template_name="userapp/password_reset_complete.html"),
         name='password_reset_complete'),
]

site_recipe/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
    <script type="text/javascript" href="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
    <link rel="stylesheet" href="https://unpkg.com/tailwindcss@^2/dist/tailwind.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/boxicons@latest/css/boxicons.min.css">
    <script type="text/javascript"
            href="https://cdn.jsdelivr.net/gh/alpinejs/alpine@v2.x.x/dist/alpine.min.js"></script>
    <script type="text/javascript" href="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>

    <title>{% block title %}  Healthy Yummy {% endblock %}</title>
</head>

<!-- navbar goes here -->
<nav class="bg-gray-100 fixed inset-x-0">
    <div class="max-w-7xl mx-auto">
        <div class="flex space-between">
            <div class="flex space-x-5">
                <!-- logo -->
                <div><a href="{% url 'index' %}" class="flex items-center py-5 px-2 text-gray-700 hover:text-gray-900">
                    <i class='bx bxs-home mr-1 text-xl mb-1 text-green-700'></i>
                    <span class="font-bold">Сладкие и Соленые</span> </a></div>
                <!-- primary nav -->
                <div class="hidden md:flex items-center space-x-1">
                    <a href="{% url 'index' %}" class="py-5 px-3 text-gray-700 hover:text-gray-900">Главная</a>
                    <a href="{% url 'recipes' %}" class="py-5 px-3 text-gray-700 hover:text-gray-900">Рецепты</a>
                    <a href="{% url 'add_recipe' %}" class="py-5 px-3 text-gray-700 hover:text-gray-900">Добавить
                        рецепт</a>
                    <a href="{% url 'categories' %}" class="py-5 px-3 text-gray-700 hover:text-gray-900">Категории
                        рецептов</a>
                    <a href="{% url 'ingredients' %}"
                       class="py-5 px-3 text-gray-700 hover:text-gray-900">Ингредиенты</a>
                </div> <!-- secondary nav -->
                <div class="hidden md:flex items-center space-x-1">
                    {% if user.is_authenticated %}
                    <a href="{% url 'userapp:profile' %}" class="font-bold py-5 px-3">{{user.username}}</a>
                    <a href="{% url 'userapp:logout' %}"
                       class="last py-2 px-3 bg-yellow-400 text-white hover:bg-yellow-300 text-sm hover:text-yellow-800 rounded transition duration-300">Выйти</a>
                </div>
                {% else %}
                <a href="{% url 'userapp:login' %}" class="py-5 px-3">Войти</a>
                <a href="{% url 'userapp:register' %}"
                   class="last py-2 px-3 bg-yellow-400 text-white hover:bg-yellow-300 text-sm hover:text-yellow-800 rounded transition duration-300">Зарегистироваться</a>
                {% endif %}
            </div>
            <!-- mobile button goes here -->
            <div class="md:hidden flex items-center">
                <button class="mobile-menu-button focus:outline-none">
                    <i class='bx bx-menu text-3xl mt-1'></i></button>
            </div>
        </div>
    </div> <!-- mobile menu -->
    <div class="mobile-menu hidden md:hidden">
        <a href="{% url 'index' %}" class="block py-2 px-4 text-sm hover:bg-gray-200">Главная</a>
        <a href="{% url 'recipes' %}" class="block py-2 px-4 text-sm hover:bg-gray-200">Рецепты</a>
        <a href="{% url 'add_recipe' %}" class="block py-2 px-4 text-sm hover:bg-gray-200">Добавить рецепт</a>
        <a href="{% url 'categories' %}" class="block py-2 px-4 text-sm hover:bg-gray-200">Категории рецептов</a>
        <a href="{% url 'ingredients' %}" class="block py-2 px-4 text-sm hover:bg-gray-200">Ингредиенты</a>
    </div>
</nav>
<!-- content goes here -->
<body>
<div class="py-32 h-screen" style="background-color: beige;">
    <div class="mx-auto p-2">
        <div class="container">
            {% block content %}
            <p>Скоро тут появится текст...</p>
            {% endblock %}
        </div>
    </div>
</div>
<footer class="mt-auto">
    <hr>
    <p class="text-center text-muted">© 2024 Сайт рецептов | Давыдов Денис</p>
</footer>

</body>


</html>